### ISSUE TITLE
Make it build with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by malmgrenola** [nxtedition/casparcg#7]
We should make sure we can build CasparCG on a Linux OS.
I suppose there is many opinions on what distro/version that should officially be supported.

A quick search in discussions indicates that it should be [Ubuntu 14.04 LTS](https://github.com/CasparCG/Server/issues/523#issuecomment-293205964).
However this is an old version and we propose that it should be Ubuntu 16.04 LTS.

I believe that 16.04 is supported until 2021 & when 18.04 LTS is released plus one year we should start supporting that version also.

Obviously we should retire support for version 16.04 LTS when Ubuntu do.

Any reflections here @5opr4ni @dotarmin ?

- [ ] Docker
- [ ] merge with 2.2.0 fork + PR

**Comment by malmgrenola** [comment]
Had a quick chat with @5opr4ni , And so far its go for above, unless @dotarmin has another opinion.

**Comment by dotarmin** [comment]
Hii!

We shouldn't stay at 14.04 LTS in my opinion. We should absolutely focus on newer version such as 16.04 LTS and 18.04 LTS when it's ready for that. Great job! 

Best regards,
Armin

**Comment by malmgrenola** [comment]
@k0d This is done for testing right?

**Comment by walterav1984** [comment]
CasparCG Server 2.10beta2 was compilable on Ubuntu 16.04 amd64 in the past even the dated ffmpeg was customizable and compilable although I'm not able to compile recent Github builds of the 2.20 branch.

Ubuntu 16.04 has a advantage over 14.04 since it can assist in building a "Snap" package of CasparCG Server which allows it to run/use mixed version of shipped/system libraries and even make the Snap run on other Linux Distributions (Fedora/Arch/etc). 

So building a good cmake/build script system for Ubuntu 16.04 will support other Distro's with the same single effort when a Snap can be crafted!

**Comment by k0d** [comment]
We are working on a good build system based on Docker containers, which output a package for the required distro. We intend to make it as generic as possible but to save time some ’hacks’ will be implemented and fixed later. I have commited an initial version for Ubuntu 17.10 (the version on my laptop) and will create more later. The idea is to use the system versions of the dependencies and to try and stick to them if we can. CEF will be an exception to this I believe.

**Comment by mint-dewit** [comment]
I think this is the right place to discuss the docker build system? (vs CasparCG/Server#676)

I tried the default instructions in the 2.2.0 branch for ubuntu 17.10 on ubuntu 16.04 LTS and got the following (truncated) output:

```
[ 99%] Building CXX object shell/CMakeFiles/casparcg.dir/linux_specific.cpp.o
[100%] Building CXX object shell/CMakeFiles/casparcg.dir/stdafx.cpp.o
[100%] Linking CXX executable casparcg
/usr/bin/ld:/source/dependencies64/cef/lib/linux/libcef.so: file format not recognized; treating as linker script
/usr/bin/ld:/source/dependencies64/cef/lib/linux/libcef.so:1: syntax error
clang: error: linker command failed with exit code 1 (use -v to see invocation)
shell/CMakeFiles/casparcg.dir/build.make:214: recipe for target 'shell/casparcg' failed
make[2]: *** [shell/casparcg] Error 1
CMakeFiles/Makefile2:811: recipe for target 'shell/CMakeFiles/casparcg.dir/all' failed
make[1]: *** [shell/CMakeFiles/casparcg.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by k0d** [comment]
Its an issue with git lfs, do you have that installed? Then do a git lfs pull.

**Comment by k0d** [comment]
After some discussions with various people, I have a suggestion on what the 'official' supported versions of linux could be.

There will only be 'official' support and builds produced for the LTS versions of Ubuntu, starting 4 months after it's release (to allow for major bugs to be found) and then for 4 years from it's initial release date. Therefore we will 'officially' support a maximum of 2 versions of Ubuntu linux at one time.

16.04 will start development right away and then when ready it will enter an official supported status. It will then stop being officially supported on 20.04

18.04 will start development testing on it's release date, and then at 18.08 it will enter (pending test results) an official supported status. It will then stop being officially supported on 22.04

We will also provide __unsupported__ builds for the other releases of Ubuntu, from it's release date until the release of the next version, so with a likely lifetime of 6 months. This is to allow developers to run the latest Ubuntu version on their development machines, and to prepare for the next LTS release.

___________________________________________________________________________
Any comments, suggestions?

**Comment by dotarmin** [comment]
@k0d Sounds good and as we talked about! I think waiting four months is better instead and not six months as we talked about first. And this application life-cycle applies only to LTS releases of Ubuntu. 

Good job!

**Comment by mint-dewit** [comment]
> Its an issue with git lfs, do you have that installed? Then do a git lfs pull.

properly cloning the branch with git lfs solved my build issues.

the version of ffmpeg in the ubuntu 16.04 repository is very old (version 2.8.11) and the build generated by docker does not run currently (libavformat.so.57 not found)

**Comment by k0d** [comment]
Currently the Docker image is building CasparCG for on Ubuntu 17.10, I am working on the 16.04 docker build image and hope to have that running this week.

**Comment by k0d** [comment]
I have completed the work (stage1) to get CasparCG building for Ubuntu 17.10 and Ubuntu 16.04.

It's not merged into the official repo yet, but is available on my fork, along with some pre-built versions that I'd love it if people could test! Remember to download the right version for your OS.

https://github.com/k0d/Server/releases/tag/k0d-00002

**Comment by mint-dewit** [comment]
Tested the (surprise) 16.04 version, and was initially missing some shared libraries. (libboost-dev-all, libsfml-dev, libfreeimage-dev)
After installing these the server does starts but crashes when initializing the decklink module saying it "cannot open libDecklinkAPI.so (no such file or directory)"
This is not an issue in other builds of casparcg.

**Comment by k0d** [comment]
@baltedewit It's quite interesting it can't find that library. I assume you've installed the decklink software for linux?

if you run "ls /usr/lib/libDeckLink*" does the missing lib exist there?

**Comment by mint-dewit** [comment]
No, it does not exist. I don't have the decklink library installed since this is on my laptop.

**Comment by k0d** [comment]
Did you change the casparcg.config and add a Decklink consumer?

If not, then maybe the decklink library needs to be installed anyway, it's not something I've tested yet...

**Comment by mint-dewit** [comment]
Did not change the config file (but even then, the module should still be initialized first). Can confirm that installing the decklink drivers fixes this and that the build successfully starts. I think we should aim for having a release that does not require this library though.

HTML and color producer both work in this build, the ffmpeg producer instantly segfaults.

**Comment by Julusian** [comment]
@k0d 
I threw it through gdb on a system without decklink drivers, and in common/log.cpp remove_source_prefix is seg faulting. Changing the method to always `return file;` makes it run fine, but it obviously needs a proper fix.
```
(gdb) backtrace
#0  0x0000555555a5e6bd in caspar::log::remove_source_prefix(char const*) ()
#1  0x0000555555cd3dca in caspar::decklink::create_iterator() ()
#2  0x0000555555cd42cd in caspar::decklink::get_version[abi:cxx11]() ()
``` 
the ffmpeg producer is likely failing from the same error for @baltedewit, as that method is used all over the place.

It would be really good to have some documentation on what packages are needed to run caspar on each distro, because it is pretty tedious to try and work out what is needed.

**Comment by k0d** [comment]
Makes sense! Its to do with some hacks I put in to get it to compile. I disabled a lot of the logging code. Will fix it tomorrow! Thanks for the info Julian

**Comment by Julusian** [comment]
Another small thing is that I dont like that inside the tar files is /build/staging
Perhaps it could be a CasparCG_Server folder or one matching the resulting filename.
The resulting file is also owned by root, which is not ideal. setting it to be owned by the user who ran the script would be nicer.

Also I guess that a custom readme for each build might be good, as there is a bunch of info in there on outdated requirements for linux that will be messy to maintain for multiple distros, and installation on windows that doesnt make sense in the linux builds. I am aware that a lot of that readme is outdated with recent 2.2 changes, but seperate readmes can still be implemented if wanted with that outdated information.

**Comment by k0d** [comment]
This issue is pretty much complete, it builds in Linux (docker) just fine.

The known bugs are tracked in their own issues on the CCG github.
